from bisect import bisect_right
import json
from pathlib import Path
import re
import subprocess

# SVF appends source locations as { "ln": .., "cl": .., "fl": .. } to the strings
# returned by getSourceLoc() and toString().
_SOURCE_LOCATION_RE = re.compile(r'\{[^{}]*"ln"\s*:\s*\d+[^{}]*\}')
_C_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Bounds wider than this describe a widened-to-everything value, not a real one.
_BOUND_LIMIT = 2 ** 63


def parse_source_location(text):
    """Return the last source location embedded in an SVF string, or None."""
    if not text:
        return None
    match = None
    for match in _SOURCE_LOCATION_RE.finditer(text):
        pass  # toString() prefixes the IR instruction, so the last blob is the location
    if match is None:
        return None
    try:
        location = json.loads(match.group(0))
    except ValueError:
        return None
    if not isinstance(location, dict) or type(location.get("ln")) is not int or location["ln"] < 1:
        return None
    return location


def _finite_bounds(interval):
    """Return the (low, high) numerals of an interval, None where it is unbounded."""
    if interval.isBottom() or interval.isTop():
        return None, None
    low = interval.lb()
    high = interval.ub()
    lower = None if low.is_infinity else low.getNumeral()
    upper = None if high.is_infinity else high.getNumeral()
    if lower is not None and abs(lower) >= _BOUND_LIMIT:
        lower = None
    if upper is not None and abs(upper) >= _BOUND_LIMIT:
        upper = None
    if lower is not None and upper is not None and lower > upper:
        return None, None  # empty interval; the state is unreachable, not invariant
    return lower, upper


def _in_scope(declaration, head_location):
    """Approximate C scoping: the variable must be declared earlier in the same file.

    Debug info gives no lexical block, so a variable declared inside the loop body
    is excluded by line alone. That over-approximates a block that closed before
    the loop, which the witness linter will reject if it ever matters.
    """
    if declaration.get("fl") != head_location.get("fl"):
        return False
    return declaration["ln"] < head_location["ln"]


def _conjuncts_for(name, interval):
    """Render one variable's interval as C comparisons."""
    lower, upper = _finite_bounds(interval)
    if lower is not None and lower == upper:
        return [f"({name} == {lower})"]
    clauses = []
    if lower is not None:
        clauses.append(f"({name} >= {lower})")
    if upper is not None:
        clauses.append(f"({name} <= {upper})")
    return clauses


def invariant_at(node, state, pag, max_line=None, allowed_names=None, loop_line=None):
    """Build the c_expression holding at an ICFG node, or None when nothing holds."""
    head_location = parse_source_location(node.getSourceLoc())
    if head_location is None:
        return None
    if max_line is not None and head_location["ln"] > max_line:
        return None  # inside code appended by the nondet preprocessing, not the input
    if state is None:
        return None
    if loop_line is not None:
        head_location = head_location | {"ln": loop_line}

    # One name can belong to several variables: code generated by CIL reuses names
    # such as tmp across blocks. Only one of them is in scope here and the debug
    # info does not say which, so join their intervals. The variable actually in
    # scope is one of the candidates, so the join holds whichever it turns out to be.
    candidates = {}
    for object_id, value in state.getLocToVal().items():
        if not value.isInterval():
            continue  # addresses and other non-numeric values have no C rendering here
        variable = pag.getGNode(object_id)
        if variable is None:
            continue
        name = variable.getName()
        if not name or not _C_IDENTIFIER_RE.match(name):
            continue
        if allowed_names is not None and name not in allowed_names:
            continue
        declaration = parse_source_location(variable.toString())
        if declaration is None:
            continue  # compiler-generated storage such as retval has no source location
        if not _in_scope(declaration, head_location):
            continue
        if max_line is not None and declaration["ln"] > max_line:
            continue
        if name in candidates:
            candidates[name].join_with(value.getInterval())
        else:
            candidates[name] = value.getInterval().clone()

    clauses = []
    for name in sorted(candidates):  # sorted so the same run produces the same witness
        clauses.extend(_conjuncts_for(name, candidates[name]))

    return " && ".join(clauses) if clauses else None


def _source_loops(file_name):
    source = Path(file_name).resolve()
    try:
        process = subprocess.run(
            ["clang-21", "-x", "c", "-fsyntax-only", "-Xclang", "-ast-dump=json", str(source)],
            capture_output=True, text=True,
        )
        if process.returncode != 0:
            return []
        tree = json.loads(process.stdout)
        code = source.read_bytes()
    except (OSError, ValueError):
        return []
    line_starts = [0] + [index + 1 for index, byte in enumerate(code) if byte == 10]

    def position(offset):
        line = bisect_right(line_starts, offset)
        column = len(code[line_starts[line - 1]:offset].decode("utf-8")) + 1
        return line, column

    def walk(node):
        yield node
        for child in node.get("inner", []):
            yield from walk(child)

    def names(node):
        return {child.get("referencedDecl", {}).get("name") for child in walk(node)
                if child.get("kind") == "DeclRefExpr"}

    loops = []
    for function in tree.get("inner", []):
        if function.get("kind") != "FunctionDecl" or not any(
            child.get("kind") == "CompoundStmt" for child in function.get("inner", [])
        ):
            continue
        location = function.get("loc", {})
        if "includedFrom" in location or Path(location.get("file", source)).resolve() != source:
            continue
        declarations = {}
        escaped = set()
        for node in walk(function):
            if node.get("kind") == "VarDecl":
                declarations.setdefault(node.get("name"), []).append(node)
            if node.get("kind") == "UnaryOperator" and node.get("opcode") == "&":
                escaped.update(names(node))
        locals_ = {name for name, cursors in declarations.items()
                   if name and len(cursors) == 1 and "volatile" not in cursors[0].get("type", {}).get(
                       "desugaredQualType", cursors[0].get("type", {}).get("qualType", "")
                   ).split()}
        for loop in walk(function):
            if loop.get("kind") not in ("ForStmt", "WhileStmt", "DoStmt"):
                continue
            begin = loop.get("range", {}).get("begin", {})
            end = loop.get("range", {}).get("end", {})
            start_offset = begin.get("offset")
            end_offset = end.get("offset")
            if (type(start_offset) is not int or type(end_offset) is not int
                or not 0 <= start_offset <= end_offset < len(code)
                or Path(begin.get("file", source)).resolve() != source):
                continue
            modified = set()
            for node in walk(loop):
                if node.get("opcode") in {"=", "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=", "<<=", ">>=", "++", "--"}:
                    modified.update(names(node))
            line, column = position(start_offset)
            loops.append({"line": line, "column": column,
                          "end": position(end_offset + end.get("tokLen", 1)), "function": function["name"],
                          "allowed_names": locals_ - modified - escaped})
    return loops


def extract_loop_invariants(ae, pag, file_name, max_line=None):
    """Export stable local facts at parsed loop starts, skipping incomplete data.

    `file_name` is what the witness should report. It replaces the path SVF saw,
    which is the temporary copy that svf_run.py compiles rather than the input.
    """
    invariants = []
    seen = set()
    try:
        loops = _source_loops(file_name)
    except (OSError, ValueError):
        return invariants
    for head in getattr(ae, "cycle_head_to_cycle", {}):
        location = parse_source_location(head.getSourceLoc())
        if location is None or type(location.get("ln")) is not int or location["ln"] < 1:
            continue
        function = head.getFun()
        if function is None or not function.getName():
            continue
        column = location.get("cl")
        if type(column) is not int or column < 1:
            continue
        point = (location["ln"], column)
        matches = [loop for loop in loops if loop["function"] == function.getName()
                   and (loop["line"], loop["column"]) <= point < loop["end"]]
        if not matches:
            continue
        loop = max(matches, key=lambda item: (item["line"], item["column"]))
        state = getattr(ae, "pre_abs_trace", {}).get(head)
        value = invariant_at(head, state, pag, max_line, loop["allowed_names"], loop["line"])
        if value is None:
            continue
        entry = {
            "type": "loop_invariant",
            "file_name": file_name,
            "line": loop["line"],
            "column": loop["column"],
            "function": loop["function"],
            "value": value,
        }
        key = (entry["line"], entry["column"], entry["function"], entry["value"])
        if key in seen:
            continue
        seen.add(key)
        invariants.append(entry)
    return invariants
