import json
import re

# SVF appends source locations as { "ln": .., "cl": .., "fl": .. } to the strings
# returned by getSourceLoc() and toString().
_SOURCE_LOCATION_RE = re.compile(r'\{[^{}]*"ln"\s*:\s*\d+[^{}]*\}')
_C_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Bounds wider than this describe a widened-to-everything value, not a real one.
_BOUND_LIMIT = 2 ** 63


def parse_source_location(text):
    """Return the last source location embedded in an SVF string, or None."""
    if not text:
        return None
    match = None
    for match in _SOURCE_LOCATION_RE.finditer(text):
        pass  # toString() prefixes the IR instruction, so the last blob is the location
    if match is None:
        return None
    try:
        location = json.loads(match.group(0))
    except ValueError:
        return None
    return location if isinstance(location, dict) and "ln" in location else None


def _finite_bounds(interval):
    """Return the (low, high) numerals of an interval, None where it is unbounded."""
    if interval.isBottom() or interval.isTop():
        return None, None
    low = interval.lb()
    high = interval.ub()
    lower = None if low.is_infinity else low.getNumeral()
    upper = None if high.is_infinity else high.getNumeral()
    if lower is not None and abs(lower) >= _BOUND_LIMIT:
        lower = None
    if upper is not None and abs(upper) >= _BOUND_LIMIT:
        upper = None
    if lower is not None and upper is not None and lower > upper:
        return None, None  # empty interval; the state is unreachable, not invariant
    return lower, upper


def _in_scope(declaration, head_location):
    """Approximate C scoping: the variable must be declared earlier in the same file.

    Debug info gives no lexical block, so a variable declared inside the loop body
    is excluded by line alone. That over-approximates a block that closed before
    the loop, which the witness linter will reject if it ever matters.
    """
    if declaration.get("fl") != head_location.get("fl"):
        return False
    return declaration["ln"] < head_location["ln"]


def _conjuncts_for(name, interval):
    """Render one variable's interval as C comparisons."""
    lower, upper = _finite_bounds(interval)
    clauses = []
    if lower is not None:
        clauses.append(f"({name} >= {lower})")
    if upper is not None:
        clauses.append(f"({name} <= {upper})")
    return clauses


def invariant_at(node, state, pag, max_line=None):
    """Build the c_expression holding at an ICFG node, or None when nothing holds."""
    head_location = parse_source_location(node.getSourceLoc())
    if head_location is None:
        return None
    if max_line is not None and head_location["ln"] > max_line:
        return None  # inside code appended by the nondet preprocessing, not the input
    if state is None:
        return None

    # One name can belong to several variables: code generated by CIL reuses names
    # such as tmp across blocks. Only one of them is in scope here and the debug
    # info does not say which, so join their intervals. The variable actually in
    # scope is one of the candidates, so the join holds whichever it turns out to be.
    candidates = {}
    for object_id, value in state.getLocToVal().items():
        if not value.isInterval():
            continue  # addresses and other non-numeric values have no C rendering here
        variable = pag.getGNode(object_id)
        name = variable.getName()
        if not name or not _C_IDENTIFIER_RE.match(name):
            continue
        declaration = parse_source_location(variable.toString())
        if declaration is None:
            continue  # compiler-generated storage such as retval has no source location
        if not _in_scope(declaration, head_location):
            continue
        if max_line is not None and declaration["ln"] > max_line:
            continue
        if name in candidates:
            candidates[name].join_with(value.getInterval())
        else:
            candidates[name] = value.getInterval().clone()

    clauses = []
    for name in sorted(candidates):  # sorted so the same run produces the same witness
        clauses.extend(_conjuncts_for(name, candidates[name]))

    return " && ".join(clauses) if clauses else None


def extract_loop_invariants(ae, pag, file_name, max_line=None):
    """Collect one loop_invariant per WTO cycle head with a usable state.

    `file_name` is what the witness should report. It replaces the path SVF saw,
    which is the temporary copy that svf_run.py compiles rather than the input.
    """
    invariants = []
    seen = set()
    for head in getattr(ae, "cycle_head_to_cycle", {}):
        state = ae.pre_abs_trace.get(head)
        value = invariant_at(head, state, pag, max_line)
        if value is None:
            continue
        location = parse_source_location(head.getSourceLoc())
        function = head.getFun()
        entry = {
            "type": "loop_invariant",
            "file_name": file_name,
            "line": location["ln"],
            # Column is omitted: SVF reports the condition operand, which need not be
            # where a validator expects the loop to start.
            "column": None,
            "function": function.getName() if function else None,
            "value": value,
        }
        key = (entry["line"], entry["function"], entry["value"])
        if key in seen:
            continue
        seen.add(key)
        invariants.append(entry)
    return invariants
